import { bitrixRestGet, bitrixRestPostForm } from "@/lib/bitrix/bitrix24";
import type { AppAuth } from "@/lib/bitrix/bitrix24";

const UF_LIST: { VALUE: string }[] = [
  { VALUE: "Assinar como correntista" },
  { VALUE: "Assinar como contador" },
  { VALUE: "Assinar como administrador" },
  { VALUE: "Assinar para aprovar" },
  { VALUE: "Assinar como associado" },
  { VALUE: "Assinar como procurador" },
  { VALUE: "Assinar como fiel depositário" },
  { VALUE: "Assinar como comodatário" },
  { VALUE: "Assinar como corretor" },
  { VALUE: "Assinar como síndico(a)" },
  { VALUE: "Assinar como parte compradora" },
  { VALUE: "Assinar como responsável solidário" },
  { VALUE: "Assinar como caucionante" },
  { VALUE: "Assinar como comodante" },
  { VALUE: "Assinar como condômino" },
  { VALUE: "Assinar como anuído" },
  { VALUE: "Assinar como anuente" },
  { VALUE: "Assinar como interveniente anuente" },
  { VALUE: "Assinar como consignatário," },
  { VALUE: "Assinar como contratada" },
  { VALUE: "Assinar como contratante" },
  { VALUE: "Assinar como credor" },
  { VALUE: "Assinar como devedor" },
  { VALUE: "Assinar como diretor(a)" },
  { VALUE: "Assinar como distratado" },
  { VALUE: "Assinar como distratante" },
  { VALUE: "Assinar como empregado" },
  { VALUE: "Assinar como empregador" },
  { VALUE: "Assinar como endossatário" },
  { VALUE: "Assinar como endossante" },
  { VALUE: "Assinar como franqueado" },
  { VALUE: "Assinar como franqueador" },
  { VALUE: "Assinar como outorgado" },
  { VALUE: "Assinar como outorgante" },
  { VALUE: "Assinar como avalista" },
  { VALUE: "Assinar como cônjuge do fiador" },
  { VALUE: "Assinar como corretor de seguros" },
  { VALUE: "Assinar como segurado" },
  { VALUE: "Assinar como intermediário(a)" },
  { VALUE: "Assinar como interveniente" },
  { VALUE: "Assinar como interveniente garantidor" },
  { VALUE: "Assinar como emitente" },
  { VALUE: "Assinar como devedor solidário" },
  { VALUE: "Assinar como advogado" },
  { VALUE: "Assinar como responsável legal" },
  { VALUE: "Assinar como representante legal" },
  { VALUE: "Assinar como mutuante" },
  { VALUE: "Assinar como locatário" },
  { VALUE: "Assinar como locador" },
  { VALUE: "Assinar como licenciada" },
  { VALUE: "Assinar como licenciante" },
  { VALUE: "Assinar como gestor" },
  { VALUE: "Assinar como proprietário(a)" },
  { VALUE: "Assinar como sócio" },
  { VALUE: "Assinar como parte" },
  { VALUE: "Assinar como consignado" },
  { VALUE: "Assinar como presidente" },
  { VALUE: "Assinar para homologar" },
  { VALUE: "Assinar como corretor de imóveis" },
  { VALUE: "Assinar para acusar recebimento" },
  { VALUE: "Assinar como morador(a)" },
  { VALUE: "Assinar como secretário(a)" },
  { VALUE: "Assinar como afiançado" },
  { VALUE: "Assinar como parte vendedora" },
  { VALUE: "Assinar como prestador(a) de serviços" },
  { VALUE: "Apenas assinar" },
  { VALUE: "Apenas assinou" },
  { VALUE: "Assinar como fiador" },
  { VALUE: "Assinar como vistoriador" },
  { VALUE: "Assinar como cessionário" },
  { VALUE: "Assinar como cedente" },
  { VALUE: "Assinar como tesoureiro(a)" },
  { VALUE: "Assinar como validador" },
  { VALUE: "Assinar como testemunha" },
];

/** Paridade com `reference-clicksign` BitrixCreateFields::handle */
export async function ensureSignerContactField(
  auth: AppAuth,
): Promise<void> {
  const raw = (await bitrixRestGet(
    auth.domain,
    auth.accessToken,
    "crm.contact.userfield.list",
  )) as { result?: { FIELD_NAME?: string }[] };

  const fields = Array.isArray(raw?.result) ? raw.result : [];
  const exists = fields.some((f) => f.FIELD_NAME === "UF_CRM_SIGNER_PART");
  if (exists) return;

  await bitrixRestPostForm(
    auth.domain,
    auth.accessToken,
    "crm.contact.userfield.add",
    {
      FIELD_NAME: "UF_CRM_SIGNER_PART",
      EDIT_FORM_LABEL: "[D4Sign] Assinar como",
      LIST_COLUMN_LABEL: "[D4Sign] Assinar como",
      USER_TYPE_ID: "enumeration",
      XML_ID: "UF_CRM_SIGNER_PART",
      SETTINGS: { DEFAULT_VALUE: "" },
      MULTIPLE: "N",
      SHOW_FILTER: "N",
      SHOW_IN_LIST: "N",
      LIST: UF_LIST,
    },
  );
}
